### ISSUE TITLE
Error in ros2 launch legged_robot_ddp.launch.py 请问是什么原因

### ISSUE THREAD

**Issue by juanvon** [zhengxiang94/ocs2_ros2#1]
正常编译完，启动ocs2_legged_robot_ros下的legged_robot_ddp.launch.py时遇到报错：
![82a1718b08ca3417cfb21707ca68ffb](https://github.com/user-attachments/assets/d3cf155c-5610-4cdb-b7cc-7e2ffe4e5067)

是legged_robot_target节点导致。我使用的是WSL2虚拟机，prefix="gnome-terminal --"时无法自动新建终端窗口，因此我将后续3个需要新建终端的节点分别依次启动，在启动到legged_robot_target节点时遇到此报错，其余节点均正常启动。

**Comment by juanvon** [comment]
补充：图中的ddp_target.launch.py是我自己写的，功能对应原文件的
![image](https://github.com/user-attachments/assets/56ef7cef-461c-4081-b2b3-0c4be8e2db2c)

**Comment by pot35** [comment]
ocs2_ros2/ocs2_robotic_examples/ocs2_legged_robot_ros/src/LeggedRobotPoseCommandNode.cpp
这个文件改下
![image](https://github.com/user-attachments/assets/4f7517a5-a9f8-4342-b4b6-1b3734447daa)

**Comment by yuki981125** [comment]
请问现在问题解决得怎么样了？有试过上实物吗？我想在GO2上用OCS2，GO2只支持ROS2就很头疼

**Comment by legubiao** [comment]
WSL2下如果用不了gnome-terminal，可以把prefix改为“xterm -e”。我fork的版本目前可以在ubuntu 22和24下都跑通。
![屏幕截图 2024-08-02 232704](https://github.com/user-attachments/assets/87633c48-4ac8-4e45-a5f4-f82fdffcb7f3)
