### ISSUE TITLE
运行例程序在rviz中没有交互球

### ISSUE THREAD

**Issue by OTT123** [zhengxiang94/ocs2_ros2#2]
执行ocs2_mobile_manipulator_ros manipulator_mabi_mobile.launch.py后，没有交互球，不能重新设置command
![ocs2_issue](https://github.com/user-attachments/assets/4c8de9a9-67c2-4495-8250-8bf2f6ee670e)
可以看到设置target的node没有启动
![rqt_graph](https://github.com/user-attachments/assets/2a99d238-019d-46ee-af5a-e415063cbc6f)

**Comment by wgx-chanshi** [comment]
这个有解决吗，我也遇到了这样的问题
